### ISSUE TITLE
"YouTube - Add Watch Later Button" fails to add button in the right place

### ISSUE THREAD

**Issue by Fred-Vatin** [zachhardesty7/tamper-monkey-scripts-collection#10]
v1.5.2

Tested on Chrome and Firefox.
Some elements of youtube has changed and the script fails to add the button in the right place. It’s invisible.

**Comment by raingart** [comment]
try this (Custom player buttons > watch later)
https://github.com/raingart/Nova-YouTube-extension

**Comment by zachhardesty7** [comment]
@Fred-Vatin try the latest v2.0.0. It works on one of my browsers, but not the other. Still trying to figure out why, but maybe it works for you!

@raingart impressive work with that script/extension! I saw [your little comment](https://github.com/raingart/Nova-YouTube-extension/blob/616847ae44daf83cf72996d0049ba47cdde20a48/plugins/player/buttons-custom.js#L494) referencing my script as an alternative 🙂

**Comment by Fred-Vatin** [comment]
I use Nova now.
