### ISSUE TITLE
youtube-add-playlist-remove-video-button: no longer works

### ISSUE THREAD

**Issue by allanlaal** [zachhardesty7/tamper-monkey-scripts-collection#8]
youtube has changed sth. this userscript no longer deletes videos
tested with Watch Later playlist

**Comment by zachhardesty7** [comment]
@allanlaal agreed lol. Sorry for delay, holidays! For some reason, it seems OpenUserJS didn't get the update to 2.0.2 so I manually uploaded it. That change was just when the script was loaded, so this issue should be unrelated. 

I tested on a few playlists and stuff and it seems to be working now for me. I'm not sure I ever reproduced this bug but I can't now for sure. See if it's working for you and if not, could you try to provide some more context? A console error from Developer Tools if you can.

**Comment by allanlaal** [comment]
can confirm. works :)

@KrazyLurt always install userscripts from their Github repos by clicking Raw: https://github.com/zachhardesty7/tamper-monkey-scripts-collection/raw/master/youtube-add-playlist-remove-video-button.user.js
this way its always the newest version and you don't have to rely on the userscript portals to update their cache

**Comment by allanlaal** [comment]
fixed
